# Generated by Django 2.1.5 on 2019-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190213_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(default='#'),
        ),
    ]
