# Generated by Django 2.1.5 on 2019-02-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_fb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
    ]
