# Generated by Django 2.1.5 on 2019-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190215_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/image.jpg', upload_to='profile_pics'),
        ),
    ]
