# Generated by Django 2.1.5 on 2019-03-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190215_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(null=True),
        ),
    ]
