# Generated by Django 2.1.5 on 2019-04-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190407_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git_link',
            field=models.URLField(default='https://github.com/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta_link',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(default='https://bd.linkedin.com/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/'),
        ),
    ]
