# Generated by Django 2.1.5 on 2019-04-14 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190407_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
